import { describe, expect, it } from 'vitest';
import { ValibotGenerator } from '../../lib/generator';
import { getFileContents } from './utils/get-file-contents';

describe('headerBanner option', () => {
  it('should prepend headerBanner to the generated output', async () => {
    const schema = await getFileContents(
      'spec/generation/fixtures/input/default-behavior-schema.json'
    );

    const headerBanner = '// This is a generated file - do not edit\n';
    const parser = new ValibotGenerator(schema, 'json', {
      optionalAsNullable: false,
      headerBanner,
    });
    const parsed = parser.generate();

    expect(parsed.startsWith(headerBanner)).toBe(true);
    expect(parsed).toContain('import { InferOutput');
  });

  it('should add newline after headerBanner if not present', async () => {
    const schema = await getFileContents(
      'spec/generation/fixtures/input/default-behavior-schema.json'
    );

    const headerBanner = '// No trailing newline';
    const parser = new ValibotGenerator(schema, 'json', {
      optionalAsNullable: false,
      headerBanner,
    });
    const parsed = parser.generate();

    expect(parsed.startsWith('// No trailing newline\n')).toBe(true);
    expect(parsed).toContain('import { InferOutput');
  });

  it('should not duplicate newline when headerBanner ends with newline', async () => {
    const schema = await getFileContents(
      'spec/generation/fixtures/input/default-behavior-schema.json'
    );

    const headerBanner = '/* eslint-disable */\n';
    const parser = new ValibotGenerator(schema, 'json', {
      optionalAsNullable: false,
      headerBanner,
    });
    const parsed = parser.generate();

    expect(parsed.startsWith('/* eslint-disable */\nimport')).toBe(true);
    // Should not have double newline
    expect(parsed.startsWith('/* eslint-disable */\n\nimport')).toBe(false);
  });

  it('should work without headerBanner option', async () => {
    const schema = await getFileContents(
      'spec/generation/fixtures/input/default-behavior-schema.json'
    );

    const parser = new ValibotGenerator(schema, 'json', {
      optionalAsNullable: false,
    });
    const parsed = parser.generate();

    expect(parsed.startsWith('import {')).toBe(true);
  });

  it('should work with undefined headerBanner', async () => {
    const schema = await getFileContents(
      'spec/generation/fixtures/input/default-behavior-schema.json'
    );

    const parser = new ValibotGenerator(schema, 'json', {
      optionalAsNullable: false,
      headerBanner: undefined,
    });
    const parsed = parser.generate();

    expect(parsed.startsWith('import {')).toBe(true);
  });

  it('should support multi-line headerBanner', async () => {
    const schema = await getFileContents(
      'spec/generation/fixtures/input/default-behavior-schema.json'
    );

    const headerBanner = `/**
 * Generated by to-valibot
 * @license MIT
 */
`;
    const parser = new ValibotGenerator(schema, 'json', {
      optionalAsNullable: false,
      headerBanner,
    });
    const parsed = parser.generate();

    expect(parsed.startsWith(headerBanner)).toBe(true);
    expect(parsed).toContain('import { InferOutput');
  });
});
