name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_call:

jobs:
  install:
    name: Install packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/environment

  preview:
    name: Publish library via pkg.pr.new
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/environment
      - name: Publish library
        run: pnpx pkg-pr-new publish --compact --comment=update --pnpm

  prettier:
    name: Run Prettier in library
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/environment
      - name: Prettier check
        run: pnpm format.check

  eslint:
    name: Run ESLint in library
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/environment
      - name: ESLint check
        run: pnpm lint

  vitest:
    name: Run Vitest in library
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/environment
      - name: Vitest tests
        run: pnpm test
